# -*- coding: utf-8 -*-
"""Nlp pro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sHQ95z5U4r8Dn3Dh10HW9CW6SC1WJzjK
"""

!pip install textblob

from textblob import Word

word = Word('caat')

result = word.spellcheck()
print(result)

word = Word('appple')

result = word.spellcheck()
print(result)

from textblob import Word


def check_word_spelling(word):
    
    word = Word(word)
    
    result = word.spellcheck()
    
    if word == result[0][0]:
        print(f'Spelling of "{word}" is correct!')
    else:
        print(f'Spelling of "{word}" is not correct!')
        print(f'Correct spelling of "{word}": "{result[0][0]}" (with {result[0][1]} confidence).')


check_word_spelling('appple')

from textblob import Word
import re

sentence = 'This is a sentencee to checkk!'

words = sentence.split()

print(words)

words = [word.lower() for word in words]

print(words)

words = [re.sub(r'[^A-Za-z0-9]+', '', w7ord) for word in words]

print(words)

for word in words:
    check_word_spelling(word)

from textblob import Word
import re
sentence = 'This is a sentencee to checkk!'

def check_sentence_spelling(sentence):
    
    words = sentence.split()
    
    words = [word.lower() for word in words]
    
    words = [re.sub(r'[^A-Za-z0-9]+', '', word) for word in words]


    for word in words:
        check_word_spelling(word)